version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/version"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/latest"
    schedule:
      interval: "daily"
